### ISSUE TITLE
Consolidate efforts?

### ISSUE THREAD

**Issue by nblackburn** [RekkyRek/RantScript#5]
I author a package called `devrant-api` that contains quite a few endpoints that you are missing so was wondering if you wanted to consolidate our efforts into one?

https://github.com/nblackburn/devrant-api

**Comment by hex2f** [comment]
Such a merger would not be possible due to https://github.com/tahnik/devRantron **heavily** relying on this package and changing the syntax even slightly would result in having to rewrite a lot of code.

**Comment by nblackburn** [comment]
@RekkyRek No worries, i understand that but in the interest of the application, it would be good to get the remaining endpoints implemented so you live up to the name of `FULL devRant API`.
